// Generated by https://quicktype.io
class ActorsModel {
  String? name;
  String? profile_path;
  String? character;


  ActorsModel({
    this.name,
    this.profile_path,
    this.character,
  });

  factory ActorsModel.fromMap(Map<String, dynamic> map) {
    return ActorsModel(
      name: map['name'],
      profile_path: map['profile_path'],
      character: map['character'],
    );
  }
}


