// Generated by https://quicktype.io
class GamesModel {
  int? id,count;
  String? name;
  String? released;
  int? metacritic;
  String? background_image;
  String? description;
  String? publiname;
  String? devname;
  String? genero;
  String? plataforma;

  GamesModel({
    this.id,
    this.name,
    this.released,
    this.metacritic,
    this.background_image,
    this.description,
    this.publiname,
    this.devname,
    this.genero,
    this.count,
    this.plataforma
  });

  factory GamesModel.fromMap(Map<String, dynamic> map) {
    return GamesModel(
      id: map['id'],
      name: map['name'],
      released: map['released'],
      metacritic: map['metacritic'],
      background_image: map['background_image'],
      description: map['description'],
      
    );
  }

  factory GamesModel.fromMapPublisher(Map<String, dynamic> map) {
    return GamesModel(
      publiname: map['name'],
    );
  }
  factory GamesModel.fromMapDevelopers(Map<String, dynamic> map) {
    return GamesModel(
      devname: map['name'],
    );
  }

  factory GamesModel.fromMapgenres(Map<String, dynamic> map) {
    return GamesModel(
      genero: map['name'],
    );
  }

  factory GamesModel.fromMapPlataforms(Map<String, dynamic> map) {
    return GamesModel(
      plataforma: map['plataform'],
    );
  }


}
