// Generated by https://quicktype.io
class VideosModel {
  String? name;
  String? key;
  String? site;
  double? size;
  String? type;
  String? published_at;
  String? id;

  VideosModel({
    this.name,
    this.key,
    this.site,
    this.size,
    this.type,
    this.published_at,
    this.id,
  });

  factory VideosModel.fromMap(Map<String, dynamic> map) {
    return VideosModel(
      name: map['name'],
      key: map['key'],
      site: map['site'],
      size: map['size'] is int ? (map['size'] as int).toDouble() : map['size'],
      type: map['type'],
      published_at: map['published_at'],
      id: map['id'],
    );
  }
}


